platform :ios, '7.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'CocoaHTTPServer', '~> 2.3'
pod 'RoutingHTTPServer', '~> 1.0.0'
pod 'Masonry', '~> 0.6.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'AFNetworking', '~> 2.5.4'